# Generated by Django 5.2.10 on 2026-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_icebooking_id_alter_timeslot_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day_of_week', 'time_start']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], help_text='Оставьте пустым для всех дней', null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Базовая цена', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('time_start', 'time_end', 'day_of_week')},
        ),
    ]
