# Generated by Django 6.0.1 on 2026-01-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatschema',
            name='schema_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
